### ISSUE TITLE
[BUG] - Map format not supported

### ISSUE THREAD

**Issue by ThePapaG** [oven-lab/tuya_cloud_map_extractor#14]
**Describe the bug**
The bug seems to be that there is no map available when show path or show location is set. Disabling both of these options causes the map to load, but doesn't show me the cleaning path or the location (important to knowing the robot state in my opinion).

**To Reproduce**
1. I added the Sweeping Robot Open Service to my cloud project
2. Configured this tool with the config flow

**Version:**
Core
2023.12.3
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2

**Log entry**
```
2023-12-21 11:57:53.537 ERROR (MainThread) [custom_components.tuya_cloud_map_extractor.config_flow] not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
obj, end = self.raw_decode(s)
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 47, in parse_path
data = response.json()
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
headers, image = await validate(self.hass, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
return await hass.async_add_executor_job(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 188, in get_map
path = parse_path(response, scale=scale, header=header)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 51, in parse_path
path_data = decode_path_v1(data)
^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/v1.py", line 111, in decode_path_v1
x, y = [_deal_pl(_highLowToInt(high, low)) for high, low in _partition(point, 2)]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/v1.py", line 111, in <listcomp>
x, y = [_deal_pl(_highLowToInt(high, low)) for high, low in _partition(point, 2)]
^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
2023-12-21 11:58:58.851 WARNING (SyncWorker_8) [custom_components.tuya_cloud_map_extractor.camera] Unable to parse map data
2023-12-21 11:58:58.852 ERROR (SyncWorker_8) [custom_components.tuya_cloud_map_extractor.camera] not enough values to unpack (expected 2, got 1)
2023-12-21 12:01:15.617 WARNING (SyncWorker_4) [custom_components.tuya_cloud_map_extractor.camera] Unable to parse map data
2023-12-21 12:01:15.618 ERROR (SyncWorker_4) [custom_components.tuya_cloud_map_extractor.camera] not enough values to unpack (expected 2, got 1)
```

**Comment by oven-lab** [comment]
Check out version v1.2.1! Added error logging for this problem to helo figure it out.

**Comment by ThePapaG** [comment]
Hi! I updated and now it doesn't crash.... but I get this...
![image](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/38738958/54d6d333-2bf9-496b-9201-d9d46872edc9)

**Comment by ThePapaG** [comment]
Recently restarted home assistant and got this log

```
2023-12-26 22:31:13.953 ERROR (SyncWorker_3) [custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.main] Failed to parse path: b'AAA4AAIAAAB8AAABqfNp/Yr7M/2o+zP9vPsz/cb7Pf3a+1v9+Pt5/hb7g/4++5f+XPur/oT7v/6i+9P+rPvn/rb7+/7K/A/+1Pw3/sr8X/7K/HP+tvxz/qL8ff6Y/H3+jvyH/oT8ff5m/If+XPx9/kj8c/4+/H3+Pvxz/jT8ff4q/H3+IPxzCAARfQgAURb8c/4CBADxDmn97vxz/eT8ff3a/If90PyH/cb8c/28/Gn9svxpCADZ0Pxf/eT8af3k/HP92igAEX0gAPEWqPxf/Yr8X/12/Gn9bPx9/Wz8kf1s/Jv9dvyv/YD8r/12/KX9dhQAABwAAEgAcVX9+Px9/e4EAAAQAApYAAJ8AHVf/ZT8X/2AVAATh0gAAFgAMaX9bAQAE5tsANWH/y78m/8k/KX/LvylCADxRhr8kf78/H3+6Pxp/tT8Vf62/Df+ovwj/pj8D/6E+/v+cPvn/lL70/4++7/+Kvur/hb7l/34+4P95Pt5/cb7Zf3Q+1v9vPtR/dr7Pf3Q+yn92vsp/dC0AQK8AROyyAFxnvsz/ZT7M9gB8ASA+zP9dvsp/Wz7Kf1Y+zP9bPsz'
2023-12-26 22:31:13.953 WARNING (SyncWorker_3) [custom_components.tuya_cloud_map_extractor.camera] Unable to parse map data
2023-12-26 22:31:13.953 ERROR (SyncWorker_3) [custom_components.tuya_cloud_map_extractor.camera] not enough values to unpack (expected 2, got 1)
```

**Comment by oven-lab** [comment]
Could you perhaps enable debug logging, so i get the files from your vacuum to fix it?

Enable debug logging:
![Enable debug](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/84805366/5b5ddab5-1d28-47e8-a71d-7bf10ab434ec)

Call service camera.turn_on
![camera tunr_on](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/84805366/64c87443-a68b-41a2-9642-79f53220f36a)

Disable debug logging:
![Disable debug](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/84805366/c42a6a11-c48f-47b8-801a-eb32c69d228d)

If the logs are not downloaded automatically, download the logs:
![Download logs](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/84805366/6dc0d987-2e88-427f-bacf-1e13d0c6d437)

And upload them here.

**Comment by ThePapaG** [comment]
[error_log-1.txt](https://github.com/oven-lab/tuya_cloud_map_extractor/files/13773495/error_log-1.txt)

Sure, no worries :)

**Comment by oven-lab** [comment]
The path data doesn't seem to make any sense at all. I am working on a new local implementation to get the path data direct from the robot. Hopefully that will fix it!

**Comment by ThePapaG** [comment]
Strange. This is the path in the smart life app. It looks reasonable here. 

![Screenshot_2023-12-27-23-16-23-187-edit_com tuya smartlife](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/38738958/b9f140d3-fd68-4420-aae7-212eac51f3a7)

**Comment by oven-lab** [comment]
It is! But some of the coordinates i get are: [-51.0, -102.4], [-382.6, -2713.3], [-435.6, -2969.3]. First of, they shouldn't be negative, and they shouldn't be jumping several thousand pixels.

I'll check the OEM apps code if there is something there that i have missed.

**Comment by ThePapaG** [comment]
Is the path also vacuum variant specific encoding? (Believe I read that the maps are encoded differently based on the vacuum?). Has it been proven working on the SL60D?

**Comment by oven-lab** [comment]
It's not vendor specific per sé. Tuya has a few different versions, with different implementations. It's possible that this is a compressed format of the version that the vacuum uses. A different implementation of the same format.

The SL60D is in the supported devices. But as it is confirmed working by individual users, it is possible that the path was not enabled or not working.

**Comment by ThePapaG** [comment]
Is there any support I can give here? Generally how do you find the path? Is there a list of documented types or something?

**Comment by oven-lab** [comment]
I'm not sure how you could help, as i don't know how to proceed myself.

Generally, to find the path, you remove the header from the binary file, then do some binary magic, which i frankly do not understand. It is all just translated from the functions in the [panel demo](https://github.com/tuya/tuya-panel-demo/tree/main/examples/laserSweepRobot/src/protocol) tuya has published.

There isn't any defined standard, it is all reverse engineered from the example above. I have only implemented the bare minimum to get it working, but it is possible that the data types that are not working is compressed or something. As soon as i get enough time i will look into the open issues which seems to have the same problems.

**Comment by ThePapaG** [comment]
I've bought another one of these vacuums so now I'd really like to help hahaha. Do you have suggestions or more knowledge on what needs to be asked and I'll submit a tuya iot cloud support ticket
