### ISSUE TITLE
[BUG] - Map format not supported

### ISSUE THREAD

**Issue by pimhofstee** [oven-lab/tuya_cloud_map_extractor#18]
**Description**

Log returns a error, please see below

**To Reproduce**
When filling in Tuya credentials an error is returned: An unknown error occured. See logs for details.

**Version:**
Home Assistant
Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

**Log entry**
    header, mapDataArr = parse_map(response)
                         ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 41, in parse_map
    raise NotSupportedError("Map version " + str(header["version"]) +" is not supported.")
custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.const.NotSupportedError: Map version [68] is not supported.

After retry:

2023-12-28 20:51:01.178 ERROR (SyncWorker_2) [custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.main] Unsupported data type. Include the following data in a github issue to request the data format to be added: 200b'RIwBBQEIAIQGcgJOBnIEYgv1H/8BAP///////////////////////////3UZ+QEAEf8OAA+HFU8BZwAPAgAxArEABgIACxAAD2oADADpAAE8AEf///n0AQAg+fkPAAEfAA8CAEMBdQAAAgAHdQAPAgApGvnAAAwQAA3gAApsAAHpAAPyADT59AgBAAAIAQApAAEfAA8CAD0A/QACZwEEAgAfBAEAHh0QAQA5+f/5FAAKEAAQAAgBFwABABf5DAAxAAAAkgAAFAAAKAAEBgE/CAgICAFKAv8AD/wAHggCAAnzAAECACv5+QgBCRAADwgBDwEPAQwIAQAfAQCuAA8QAkMY9NIADwIAIwH7AA8CABgB+AMA6AADAgAF+AAMAgAAEAIh+fkMAgMIAQMuAw8CAD8f+fsAIwkCAA8DARgBAgAA2QEI/AAIDAAIAgAAJgAFBgEAAgAQ+RcBAEYBDwIALjr09PREAA8IAWII7QAPAgAIMPkAAP4ABgIADxIDNgBXAg8IAZcdAAgBAA4CDxACMQAIAQoKAQ8QAokNCAERCCkFDwkBMAJpBAgSAg8IAaAf9B8DMQASAg8IAakALQQPCAEwAF8DCgIAAfoFDxYCKwEFBg8CABgAIwkPAgAUAPcABwIAAkAGDwgBMQAgBAkCABEEFwEBDgEPAgAmDwQBGAACAA8IAScgCAhIBw8IASgEOwAv+fTtACYPAgAIAN0ADwIAGA8IASQBFQMPCAEpAFsEA2UFDwgBnwH+AAECAAUKAATVAQ8CAB0BCAMCPQAPCAGfDwIAAALLAA8CAB4AIwYDCAEf+QgB6gEJAQKcCw8fBEIfBBwEGAACAA8gBCQFAgAPEAIkAp0MAkMJD+0ECA8CACgA3QAPAgAYAggBAgYADwIACwIoBwwCAA8IASUDLgcPJQgrDwIACQ8EARgAAgABlQEPZQ4IAhwBACMAAggBACQGCAIADwgBvA8CABIAAAECBgAGAgAPCAG1AvABDwIAEgL9AAsRAg8IAeYLAgAPCAEnAoMCD+MDCQ8CACoA9QMPAgAYDwoCEgICAAsCAQICAA8IASYBKQUfBCgFdgLjAA8CABIC+QALAgAPCAEqD/EBKg8CAAwPDAIYAAIADwIBEgICAAFYDQsCAA+AECgPCwIoAlMDDwIACRAc3AAPAgAZAuMADwIAEgwrBgACAA8IAV4AUgQPdQAPDwgBAQ/AGAwPAwESAQIACyoGAQIAD5MADw8CAAYA0gAPAgAeEPk2AA91AA8PCAGZDxkDIQSdHQ9dAQYDAgAPCAEBGhDPGgsCAAHqAQ8CABMPEAI8DwgBIA8BAQ8DAgAPCAECDwIACg8DARMBAgAPCAFwA+cADwIADg8IASMPZg0RAPMdARIECgIAD6sDDw8CAAcPGAMfBKUHBAgADwIABg8IASMPAgAFCyABDxACcAABAQ8oBSUPAgALCAQBAZEHBxEAABAABw8ABgoCBhIBD7IDFg8CAAAPEAIfAcgWDwgBRgX3AQBuAQUNAAAJAwgPABv54BwCAgAPCAEtDwwBIA8IAUYEAgAB1AACCAEDBgAEDwAAAgAPCAEDDyAEWwMCAA91AA8PIAQrAAgDAwIBAPoAAQwjAQkAAAIADwgB2gDxAA8CAAQPCAH//1IPJQUiDyAEUg8UAwQAAgAPGAM/D1kLIAICAA8oBUwAJwUA8gAPAgADDwgBPABtAAAMCA8CACEPCAFEAiMGAD8IBAoADwIAAQ8IAT0BFgkPBgEhDwgBRgQCAA8IAQwS/zoJCgIAD5sBDw8CAAQAHAQPCAGtB5kSDwgBwg8fBAkXAP0ABwIADwgBJwAfBAAVAg8CACAB+QoPAgAKD1AKBw+NEQUEFQMAAgAPCAFZAQIADwgBHgE9AQ8HAQ8PCAEIBAIADBABAAABBAIAAGMACCsFABAABBwAD3cPAw8QAicBAgAAYQAPAgAdATkADwIADQ8IAQ8MAgAA4gAFAgABRC0FDgABaA0GGAEGbQ8HAgAPCAErDwIAEiD5/zMiBAIADzMAEg8QAhAMAgAG9gAC+QAIdS4KiA8PCAFlCQcBDwkBFA8QAkgPKAU8DwIAGAD+AAcCAA86ABEPCAEtDyAECAcIAQcaAg8YA1ALEAIPCQESDwgBLA8CAAkHUAoPCAFbAUolCgIADxMCDg8IAVMHAgAPEAJQDwgBAAC5BA0CAAp5BgwIBQ8CAA0PAwIJCQIABxACBwIADwgBUQ4JAQJoJwwCABUcAQAP6B1JDwgBZgcSAgHrMAAHAAE9IQcCAAUCAQUCAA8AAg0MAgAC9AEKIAUPAgACDwgBeQAbAQXyAA8CAAMM6AAPAgANAfQACD0JDwIABQ5wDgAvBQCUAA8CAE4MAQMA7wkf9P8AAwUCAA/4AA0MAgAB9wAPCAEkH/kIAVQOAgAf+RACeQAgIw8QAjcN9QEPAgAKDw8CDQ8IIgAPAgALDxACDQCOAAAkAAJGKgoCAAAcAA/DBgIPAgAhBhYGAw4FAJowAQYABQIABhkADwcBDg8IASMPAgAIAewAAQIAD9gbAg8QAjgF3AAIAgcKAgAa+Q8ADwIACQ/+AQsOAgAPAwEIBQIAAQcBDzAGTQ/yAw4PAgAbCOoADBolDwIAAQXtAA8CAAgBfA8HCAEHawwPEAJBDwIAMgbsAA8GAREPCAEZACcHDQIADwgBOA8PAwcPAgAhANwAAQIAD2MLFA8HAggFAgABEAIIACEGAgAPCAE3AB0ND/EAIQ8CAAQBBAEPBgEWDwgBAgIPBAgCAAAGAQ8IAU4PEAIACxoBDyIAAA8CAAYA3AAL40EPAgAKAOEACQIADwsHAAMJAQYGAgYCAA8QAjUAdgEP1AAGDwIAIQD1AA8TAxQBAgAJBAEAmxMFEQgAmwADDQACCQEG/gAHAgADIgAPAgAcAVwACQIADxQIEQ8CABkPBgEbDwgBAACjFAKiAAAWAQPgAAENAAf+AAYCAA8IASQFHAkFAgAP5QAZDwIADwDCAADfAA8CABYBBQIGAgACGBcFEAAF5gAAKwUG/QAHAgAFIgAPAgAaDy0IPA0CAADHAAyiGA8CAAsF8wACAgAC1wACDAAHEAIBwBcH/gAGAgACMQAPAgAdCwEFDwIAPQAHAQUeSAAbAg8CAAEKGAEB7wAGAgAB1wAHDwACQQAAVgAPCAEFATIADwIAHQ8IAU0AkAACuwAF5AQMAgALLwIG9AABAgAB1gABCgAHAgAAFQANGEUEAgAAHQAPAgAeDwgBUQ8CAAwPCAG2AewBDwIABA8EAQwAAgAPCAE8D0EIIw8QAjEP7gASDwIABw8IAQ4n+f8TAwECAAD7Ag8YAwUPCAFnAgYEDwIAJg8IAQ0BKwgBAgAAdAICCQAAOgYPKAUEDwgBbACjAQ8CACMLhw4B6QAGAgAAaBAEDgADBgECaA0PEAKBDxQCKg8QAgsG/QAPCAHxABIDAAIAAA4BARwBAScCBCoHCQIADxgDaQ8QAjAFFgIB6QAHAgAB9AADdgMCDAABDwAALgMJAAEEAgAPCAFpAN8JDx0EIwA6AAFQCg8IAQcBJQANAgAPCAGCDxACKwEDAQEFAAACAAcLAgECAAMLAgwCAA8IAb8DVg8ABAEAAgAC/QAB/gICAgAMAgECAgAAHAACuhkGAgAB0xgPGANpDxACLAICAAAFAQUIAQLtAA8CAAsNqBUAbAgBPQQPAgAfD1AKMQ8IAS0CuBMEGQMCEAIPygARDAgBDzsCBQ8CABEPCAEzAIcBD24AEQ8CAAIEAQEDAgAPCAEYAQgDBQIADxEDIwMCAA8IAQwMrBQMEAACAgAPywQEDwIAFA8IASYAWwQFBgEPCAEtD9oAAw8CAAUPNwEDDwgBLAUbBAECAAIyCAHmAA8CAA8IGwMPEAIqDxICDg8CABEPCAErAQIABhUCDyoHBg8CAAEPCAE5BdcdDwIAJg8IATsPDQIWChgDD4UALQ+qFTAPgwAtANEAARQDABYCDywGEwMCAAChBQQCAAMTAA8CACUPCAEvD4MALgAIAQTOAA8ACCQPAgAvAXsADwIAKw+FAC8PAgD/////////////////////41D//////w=='b'eydyZXN1bHQnOiBbeydtYXBfdHlwZSc6IDAsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktZXUtc3RvcmFnZS1wZXJtYW5lbnQudHV5YWV1LmNvbS81MDdmMTYtMTU2OTg4MTE0LTEyM3dkYjA4N2ZhYWRjMmNlMDU3L2NvbW1vbi9sYXlvdXQvbGF5LmJpbj9DQz1kODQ4ZWY3NjEyYTI0ZDRjOGM1Y2VmNTM4YjljMjJiYiZDUz1mNTA5YjFjYTY5YTBiNzM1ZTQ5MTdiMzRjZDA5NDllZjhlOGJkN2Q0ODJlYjAzMTczMmI2YjM2NmZiMmYxNTA5JkNFPTE3MDM3OTY2NjEwMTcmQ0E9VjEmQ1I9Mid9LCB7J21hcF90eXBlJzogMSwgJ21hcF91cmwnOiAnaHR0cHM6Ly90eS1ldS1zdG9yYWdlLXBlcm1hbmVudC50dXlhZXUuY29tLzUwN2YxNi0xNTY5ODgxMTQtMTIzd2RiMDg3ZmFhZGMyY2UwNTcvY29tbW9uL3JvdXRlL3JvdS5iaW4/Q0M9ZDg0OGVmNzYxMmEyNGQ0YzhjNWNlZjUzOGI5YzIyYmImQ1M9NTY4YTk2ZWQyOTVhM2RiODQwZDNkZWIxNjQ3ODNlNWY3ZjZhY2FjZDc4ODdhNDMzM2MyNjBkN2YzYTc2ZDI1NSZDRT0xNzAzNzk2NjYxMDIwJkNBPVYxJkNSPTInfSwgeydtYXBfdHlwZSc6IDMsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktZXUtc3RvcmFnZS1wZXJtYW5lbnQudHV5YWV1LmNvbS81MDdmMTYtMTU2OTg4MTE0LTEyM3dkYjA4N2ZhYWRjMmNlMDU3L2NvbW1vbi9yb3V0ZS9uYXYuYmluP0NDPWQ4NDhlZjc2MTJhMjRkNGM4YzVjZWY1MzhiOWMyMmJiJkNTPTY0ZjE1YjhjZWZhZjkzYmNiZDIyZGE0OGMyMDE1YjYxZmVlYzYwM2RhZGZiZTMzZjM0MjcwMjc4MDg1OTAwMzImQ0U9MTcwMzc5NjY2MTAyNCZDQT1WMSZDUj0yJ31dLCAnc3VjY2Vzcyc6IFRydWUsICd0JzogMTcwMzc5MzA2MTAyNywgJ3RpZCc6ICc2ZDMxYWQzZWE1YmExMWVlOTg3ZTFhYjdmODQwMzJlNid9' Thank you!
2023-12-28 20:51:01.183 ERROR (MainThread) [custom_components.tuya_cloud_map_extractor.config_flow] Map version [68] is not supported.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 30, in parse_map
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
    headers, image = await validate(self.hass, user_input)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 154, in get_map
    raise e
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 144, in get_map
    header, mapDataArr = parse_map(response)
                         ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 41, in parse_map
    raise NotSupportedError("Map version " + str(header["version"]) +" is not supported.")
custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.const.NotSupportedError: Map version [68] is not supported.

**Comment by oven-lab** [comment]
Will look into!
