### ISSUE TITLE
[BUG] - No permissions. This API is not subscribed.

### ISSUE THREAD

**Issue by jflorido94** [oven-lab/tuya_cloud_map_extractor#28]
Hi, Im adding this on my home assistant for manage my realme TechLife Vacuum

I get this error. 
```('Request failed - Response: ', {'code': 28841101, 'msg': 'No permissions. This API is not subscribed.', 'success': False, 't': 1707133829609, 'tid': 'c2786c25c41c11ee84c772fd0bbfcb23'})```

Can someone tell me what happend and how solve it?

Thank you

**Comment by OrZ88** [comment]
SAme here.

```
Logger: custom_components.tuya_cloud_map_extractor.config_flow
Source: custom_components/tuya_cloud_map_extractor/config_flow.py:57
Integration: Tuya Cloud Map Extractor ([documentation](https://github.com/oven-lab/tuya_cloud_map_extractor/blob/main/README.md), [issues](https://github.com/oven-lab/tuya_cloud_map_extractor/issues))
First occurred: 11:35:13 (3 occurrences)
Last logged: 11:35:26

('Request failed - Response: ', {'code': 28841101, 'msg': 'No permissions. This API is not subscribed.', 'success': False, 't': 1707500013393, 'tid': '12a5b7dfc8001000000000000000000000000007452'})
('Request failed - Response: ', {'code': 28841101, 'msg': 'No permissions. This API is not subscribed.', 'success': False, 't': 1707560000017762, 'tid': '15451f670000000000000000000000000d90a'})
('Request failed - Response: ', {'code': 28841101, 'msg': 'No permissions. This API is not subscribed.', 'success': False, 't': 170756000006148, 'tid': '1a4445e4c8000000000000000000b272d90a'})
Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
    headers, image = await validate(self.hass, user_input)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 124, in get_map
    link = get_download_link(server, client_id, secret_key, device_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/tuya.py", line 68, in get_download_link
    raise RuntimeError("Request failed - Response: ", response)
RuntimeError: ('Request failed - Response: ', {'code': 28841101, 'msg': 'No permissions. This API is not subscribed.', 'success': False, 't': 17070000000000000393, 'tid': '12a5b7d000000000000000057452'})
```

**Comment by oven-lab** [comment]
Did you both make sure that you added the robot vacuum api in the tuya cloud as directed by the readme?

**Comment by backcountrymountains** [comment]
I had to navigate to a slightly different page at the ```iot.tuya.com``` site: ```Sidebar > Cloud > Cloud Services``` and then I searched for "sweeping". 
![image](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/29560911/46455657-24a4-4e2c-9e09-bebdbff7c217)
![image](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/29560911/4f678d6c-f030-4e57-9eb4-23abde87c045)

I am in ```Western US```

This map decoding is an amazing feat!
