### ISSUE TITLE
[BUG] - Unsupported data type

### ISSUE THREAD

**Issue by brunokelo** [oven-lab/tuya_cloud_map_extractor#38]
Map version [163] is not supported.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 30, in parse_map
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
    headers, image = await validate(self.hass, user_input)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 154, in get_map
    raise e
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 144, in get_map
    header, mapDataArr = parse_map(response)
                         ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 41, in parse_map
    raise NotSupportedError("Map version " + str(header["version"]) +" is not supported.")
custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.const.NotSupportedError: Map version [163] is not supported.

Registrador: custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.main
Fonte: custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py:147
integração: tuya_cloud_map_extractor ([documentação](https://github.com/oven-lab/tuya_cloud_map_extractor/blob/main/README.md), [problemas](https://github.com/oven-lab/tuya_cloud_map_extractor/issues))
Ocorreu pela primeira vez: 11:28:13 (1 ocorrências)
Último registro: 11:28:13

Unsupported data type. Include the following data in a github issue to request the data format to be added: 200b'o74BBQDVAagFZAUKBEYM1RpdH/8BAP///////////////////////////////////////////////5U/9PT0hyS/EPQBAA/XALYAzQAw9PT/BQACAgAP2gCnBm4CAsoACgIAH/nZAKMCxQAFCQALAgAP1QCjA8UAB3UCCQIAD9UA/3cFlgEPqgEDL///qgGgAtQAD9EAAwZBBA8CAJwBuwAIxQULAgAPzwCcAQIAA8MAD6oBBg9/AqIP1QAOD/4EoAC1AA8CAA0PKQSeD9EADQACAA/VAJ0AtAAPAgAOD9UAwR/51QCcD6UBDgACAA/UAJwPyAUHCAIAD6oBnAi7AA8CAAgPqwGbD8kACAgCAA/VAJoIuQAPAgAJD9UA//9FD3ICCQkCAA9/ApkJuQAPAgAJD9UAmA/HAAkKAgAP1QD/bQqNAQ8CAAoPqgGXD8cACgoCAA/VAJYKtwAPAgALD9UA/2sPmwELCwIAD6oBlQu3AA8CAAsP1QCUD8UACwwCAA/VAP//QCz5+WMCDwIACQ9/ApIPwQAJDwIAAQ/VAP9nD3sCGg9OEpUPUQMbD34ClA+qARoP9ROSAE8CAH8BDwIAFQ8lBJUPqgEbAZobDwIAjA+qAcE/9AAAeQIVAgIAD38CkS/0AAEAGyD0+QEAD34CjA/TABsSANgBD64BQwAuAQ9aAAkBIAALAgAEXgEDFwACDwAPqQEdD9UAMQOBAAMCAAKIAAACAACwBA/VAAoCAAMIAgAFPwAAPAAFPgAP1QAfAK0BD3sACQ8CAA8CgQADAgACSwAC4QAAtAQPPwAIATgAGggBAAA5AAAzABD5FwAEPgABpQAPAgAdBD0ADwIAJAGBAAQCACD5/5gAARMAAAUAAuQADwIAAwDVAAQ3AAcCAAFAAAA8AAQ+AB/50AAdAQIAD9UAOgOQAAMCAA/VACAAAgAC2QAAtQEABgABpQAJAgAAFgABAgAJFgAJAgAP1QAnAVkACcYACwIAD9UAJAfYAC/09FMDIg9UAygAQgIKmwELAgAP1QAnAAIAAF8AD9MAIw+qASoAHwQPqgFDAAIAD9MAJw/VAIgAnQAPAgAlEPSSAw8CACMAIQIPqgFHD9EAJQACAAReBg8CACABKgQAKgIPAgAED1QDKwCdAA8CACUP1QAoAAIAD6oBgw//BCgAAgAP1QD//4sBSgQPAgAED/wJAwcCAA8lBCUBAgAPKAknAAIAD1QDCQFBBw8CAAcAIQAPAgAIAZ0ADwIAJQ/VAEkcCNMAD8UACAwCAA/QACUBAgAP1QBKDwIAKAGdAA8CACUP1QD//zEC6xIP+g4jD1IISA8CACsCFwMP1QBYB3wGD7oAKw8CAAgC1QAf/ysEIwM9AA8CABoV+Z0FD6gGCw8CACkEmAAP1gAiBD0ADwIAGST59K8AD9UAuQTUAA/VAFAPgQIiD6oBIg/VAFkDfhEPCgUaD9UAjg+rARILJgUP1QCPA6sBDwIACg/VADEDxhQP0gVIFwhtAQ/PAAoPAgACBz0ADwIAFgCoBgBXAwIGAA8CADQJTQAAYgAFjwAPuAACDwIACg/VACIDyAAJiAAPAgAtCU0AD9UAaA8CAEkIbQEPlgEKBQIAB1gDCD0ADwIAFQ+eBkcGAgAImAAFuAAPAgAVCD0ADwIAFQ/VAF0P1gUSCAIAD9UA//8+D4ACHQ9/AiIPfQdbD9UAUwQsBAPcAA8CAEIKbQEPKwkRBwIACj0ADwIAEwAbBwMCAA/RAEIAAgALmAAHsgAPAgAQCz0ADwIAEg/TBV4PqwEdD9UAlA8rBBsP1QCVD1YDGg/VADwDawMPAgANADYDCwIACRUAAEAAAHYCBgIAD9UAagaHAA8CAAgJwQADAgAJqQMO1QAPgAIaD6oBPQ/LAAgHAgAAtQAAAgAD0QAPAgAADZgAD6sBGQ09AA8CABAJVQEKAgAPkx8JCAIAANIAD+cGCg2YAA/VAJEBDAEPHgEIDdUAD9YAGQ49AA8CAA8PjAAID6oBFg/VAPQPKwQYD6oBlw+AAhgP1QD/VAOxAw9tAQEPywoQAgIADz0AAQ8CAA0DeAAPAgABDykESA/VAP8jBaAaDQIAD6oBSg8ABRYPfwIiD9UA/wYBJgkPAgAKAEYDDAIAAggEDwIADg+qATMGngAMhwAPAgA7D88ADgICAA/VADQPvAA7DwIABg8AChQP1QCbDysEFA/VAJwPqwETD9UAIxsUAQAAygUGWAMPAgALD1wCBg8CABEP1QBeDN4nCQIAAY0pAAIAAAABDwIAKA/WABAAVAEPYgAfD6oBBC/0HAEACCH5+R0AD9UAUQ/RAB8AAgAP1QAEEQy3AA8CAAUC1QAfHO8CIQkCAA+rAQ4JLgAPAgAXK/n5UwMQFFQCD9UArB//1QCJD5wBFwsCAA7VAB/5qgEIEfl6AgEFAA9/AjAPAQ8NC6sADwIAFw3VAAAqAw9/AgYAjgQAAgAA1AAP1QBPAAoDDwIAIg/VABsBAgAE1gAA/wAPAgArDyoEDA/VAF0ArQEP1QAvDysJDA+kBiEBAgAPqgEiA68BD0oBJgUCAAKKCw8CAAYPYQAlD9UAIQOFAgWbAA8CACgP0AAGAQIAD9UAVwGpAQGsAQ/NACgEAgAPVgMMBCcADwIAHA+qAR8E1QAfHEgBJQgCAA/VAAwYACwADwIAFw/VAB8FAgAP1QAxD6sGDQ/WACMP1QCND7ZpIg/VAI4P1gAhD9UAbQ+rBgwP1QA5BTgDDwIACQ9UAzIP1QAPD2cAIA+qAQMPzAAJBQIAAFgIDwIAFA+5BAkIWz8O4wAP1QAzAFENA4cLDwIADQDTDw8CABIPbQELB9YAD9UAAA8SAQsPAgADDaoBD9UAGA8CABQP1QAQBK8GD9UAAA9iCiEP1QBQD6QMDgbuAR3/jEMPEgENDwIAAg/VAHEBAgAF2gAB9gkFAgAP1QCnBdEAAQIABdEAAAIAD9UAtQRhAwECAA/VAK0Bv2QABQABzgADAgAP1QCnAMoAAtAAATZsA9AAAQIADy5sIg8pBHUA0AAA3AAANQQI1wAP0gUhDvgTD6gGPw/TBQ4MAgAFVwMf/9UAuACyAQF8Ag/VAP+QAQIAAPcOD38CuQECAAGBAg8pBLcDAgAB1gAP1QD//2kBgQIPfwK9ATIOD9UAvgARCg/VAL0B1AAPpngiD9EKAQUuFw8CADQPbgEiD9UAPD/5+RTOADQDAgAP1QAjAqkBAb4LDwIAHQ6qAQACAAOOAA8CADQP1QAmAtoAD2ETCw8CAAEP1QCGAKkBBAYADwIAHQ/VAIkChQwPIhggD9UAHw9HBB4PHR4iAqkBAQgAAAcADwIAGw/VAAIPcCUJDz4XDABiHAK2FgYpAA+SABsCAgAPogEiBAIAD9UAAg8hBAoPuAMKANAAAdoADygADA8CAA4P1QB6AaABANQADxMeMg8CACQPqgE8AQIAAdkAD3YCIw8CADMP1QBBDwIAbg/VAA8BTgIALAMCAgAPSgcjDwIAWw/VAA8B4iIP1QD//1wAvAQAAgABRgMBBwAPfwKtAM4AAtgDAAoABAIAAeAAAAIADykEowoyCAHVAAMHAAMCAALyAA8CAIkO/gQK1QAArRcAKywA0QAPyACJCQIAD9UAEQDyGQ8DESQPAgBjD9UA4wMCAA+qAbsGAgALbQMPAgCID38CDgoCAAAwBA8CAA4KMwAPAgBgD9UAAgm3AAmVAAACZAcCAAAPAAAEAAkCAA/SAW8P1QADB6UACqMAOPn0BAEAE/kEAAcCAAwyAA8CAGEP1QAEBqYAB9UADsIAD9UAAB8E/hEgDwIAPQ/VAAMfENUAAAETAADGAAcCAAGoAgYQAAEeAA/VAJgDugABtwAHAgAA1gAGDwABDAAPdwE9DwIAIA+qAQMBngACAgABthMFEAAP1QAAAicAAQIAAQ0AB7ACDwIACAC2Aw8fAAgPAgArD9UAAgfGAABIAxH5rQABAgAM1QAKAgABKAAAvQEP2QAPD9UAYQCtAQGjAADVAAEGAAICAA/VAAoCMwAArwAP1QCBAJ4AAAIADskAD9UACyD//yAAD1IJEw+uFCoPAgAMD38CAgj+BArJAAC1AA8CAAYFCAEPSQ4PAM8BD5oADA8CACgP1QARAK0ABAIAD9IABgACAAQfAA/VAA0A0wAP1QBcKvn5qgEPAgAfD9UADADSAA9+AkkP8CcASRQU9PR/Ag8CAB8P1QCBIhQU1QAPQQMKDwIACQ/VABIPNAMoDwIADQ5UAwACAAHVAAQiAw8CAB8P1QASD08JSA/VAAkPzgAfAwIAD9UAhw+pAScP1QAMASYED6oBYw/UACgP1QCIA0sCDwIAIQ+qAYUP+gQmAAIAD9UAEg/DBA0PAgAoDykEBA99AikP1QAMAVADAAIAD7YAKA8CAAwP1QANAB8JAKgADwIAGg+qAQoA0AABAgAPmgAMDwIAKA/VAAMCQg0A0QAASBcP0QAaAAIAD9UAghD5HycB0QAAAgAPXwMfD9UACQRSEwBaAA8CAEUPqgEBDOwTD9YAHg/VAH8FogEFAgAP1QA2EPkZGgICAAAKAgVhAA8CAD0OqgEOiw8AgQAPAgAcD6cAAwR7AgUCAA8nAAMPAgAuD9UAEQ8CADcEzgAEsgEPWgA3CQIAD9UAVwACAiL0GNcAD9UAqwi2AlH09BgYGE4DAtoAD9QKRw+qAQAOKgQDAgAIogAPAgACASgACRoAAbsAAF8SAAYAERjVAAIMAAAIAABpAAEuAAE4AA8CADgO1QAAwjcPawAEAFkHDwIACACeAAAMBAflBAcCAADTAAACAAYTAADVAACJAgA4AA8CADoP1QACAc8PAdkACAIAD9UADgCfBgDVAAB5LQC/AA8CABQABgEP1AA6D3kRAgPPDwUCAAL+CTX5+f8SAA8CAAMF1QAP1AAaANYADwgFPA+qAQcPAgAfD9UAKQ/XADoP1QA9ACQDD6oBIQ/VAJQQ+VoCDwIAEgDTAA/VAIoAnwBv9Pn0GBj51QAbDyoEOg9/Aj0B1QAPfwIgD9UAvgCIAw/VAIkS+XkHD3sCFz8YGBimBj0PfwI/AYQhAFQDDwIAGA+BFj4PVAM9AdUAD1QDHQBeAQ8CADkP1QA/AcYKD6gBGA+qAWgCKwkPAgALAFIID9UAIQ+lATkBAgAPqgE5APQKAagBDygEGg/VAAgAHAsBpgAPAgAcDtUAAJkLAaAaDwIAHgCqAR/5ewIcD/0ECQCdAw/PABwCAgAP1QAAAG8BD9EAHgACAAHVAACoAA8CABkP0QUHANQAD6oBNgAZAwCkAA8CAB4P1QAiAlwBDwIAAAHUAA/VALwC1AAASQoP8QAADwIADA9/AgIPqgESAnAXCAIAAIAADyQEHB8YnwAFAdAAAQIAD6ACBw8CAAYP1QAqC7sVD9UAOAHPAAICAA/VAFoACiMIqAEP1QAiD20BBALPAAECAAAoBg8CAB0PqgEnAIECAAYABgIABqoBD4UCFQDqAg+KAQAHPgUPqgFdBKsBBYUCD9UAIA+lCwIH1AAA/RQPqAEdD6oBBgCCBwMCAAaKAQYCAALIAABqDAACAAQYAACAAA+kARUBAgAQ/wYADaoBABUABQIAD6oBOATWAAAKAASzAAsCAADOAAAWAQe/Gg/VAB0B1AANTw0F0AABAgAPVAgiD1QDAwPLAABFAQKVAQ4CAASnAQapAQE/IQ+qARUBEkQBtwABGgEGAgABFAAGAgAP1QA5ArgUD9UADAFXAwfvAA+qARkAxgACuwAACgAGAgACFAAGAgAP1QBhCUQiD9UAGADGAAK6AAAKAAUCAAITAAcCAA8nCTkA1AoEAgAHiwEIAgADWxcIngIP1QAYAM0AAAYAClIIARIACAIAD9QAIw9MFwAAdAIGSwMP1QBHAb0AAGsABQIAARIACAIAD9QAJA/VAC8HqwEPqgEaAQIABdAAAAIAARIABwIAD9MAJQ/+BAYBBgQAAgAPqgEGAn4CCQIAD9UAHgCBAAUCAAfPAAACAA8iBCIDAgAP0wUFBK4KD9UABg8CAAAP1QAdA4MAAgIAAMkABgIAAEsADwIAJw/VAAUEtAAP1QBIAr0DAwIABtAAAAIAD7maKAACAA/VAHQAygAGAgAPnAsjBgIAD9UADASGAg8CABIANAIPUggVCiAJARAABQIAAHMMCccBDwIACQAtAAwgAA/VAAwPAgAaD9UAJgXPAAECAACnAABLAA8CABEBLAADAgAGMAAP1QAEAicJDwIAHACKAA+qASEBywAFAgACowAGogAPAgAKAS0AQSQkJCQJAAQFBg/VAHAFzwAAAgACnQAEngAPAgAOAdEAAwIABTsADtRtASMTD4UGAA8CABAPqgEiAMoABQIABZgADwIAFQjVAAACAAFBAA/VAAUE+QkPAgAMCuoAD9UAIQXQAAA6BAGTAAK5Wg8pBBQM1QABiQIP1QAGAq8AAQQJAQUAAAIAD+IAAAAXAAUCAA/VABEGdAMBZA4BzQAEAgAC4SMAWBwP1QAUAk8DDAIAD9UAEg8CAAgF8AABAgAP1QAbAWICBNAAAQIAAUoDANIAD/4EFQ+oAQAAqwEP1QBpAGICAc0ABAIAANUAAdIAD9UARQNrAgGCAQ8CAAcPqgEpEBhjAATQAAECAAAeygHSAAFZAw8CABAPqgEYAG0AAlUDCrQADwIAAAohAA9/AhsNAgAArCUABAAP0wAVD9UAGgHXBQavAA+vAQkGJgAAAgAP1QAqAgIkAdUAALAADwIAEg+qARgA1QAHygAKuQAKAgAKHAAP1QAqAbkUAEIADwIAGgEaBAsCAA/+BAIA8CcKrgAPAgAGCicAAJMABrMFDwIAAw8gAAkPzwAaAQIAC88AAgIAD9UAegD9BA8CABwCxgALAgAP1QB7AY8HDwIAGgvPAAICAA/VAGAAXAUPmgIDD0cIFAgCAALGAAsCAA/VAF8A1gAP1AADD+EYIQvPAAICAA/VAGAPAgAHD8wFGAQCAALGAAsCAA/VAAMA6AoNAgAPAgUCD/4EHw8CAAgP1QBKANAABAsBBQIAD9YAAw/VADoFbAAPAgAXC6QBAgIAD6oBAg9UAAMKwAADAgAKFQAPqAYRDwIABQ91AAMPAgANAsYACwIAD9UAdQ+9AA0PAgAFDygJAg/VABcPfwJID7IABQ8CABAM1QACwAcPUA0FCwIAD/8TBQ9/Ai4ChgAPAgAmB/sOCEoAD04SBQoCAAq9AAYCAAoYAA9UAx8KZgAPAgAfA9UACNEAAAIAD9UAaAB/AA8CAEMP1QBkDFwBDwIAOw/VAGMPxAA7DQIAD9UAFA8qBAQPVAMiDYQADwIAPg/VABMHWxwJAgAP1QAeD3cCSwQCAA/VAFoP0wBTD9UAWgBvAA8CAFMPqgFVD84AUwMCAA1TCA+iCwABAgAKPwMCAgAA0AsJAgAAozwOswoAixUPAgBbDKsBD4IABQm9AAQCAA+rAAAAGwAK2AAAaQgPAgBcD9UAFQ8CABgKBxMPexAgDwIALgyAAg+qAQUPAgAYAWcVBgIAD9EBAg8CAEwLqwEAPwIBKz0BBwAPAgASCKEAATEABtEAAAIAARMADywBMA8CABkv+SABAAAAoygPFwAAPiAgIC8ACbUADh8AESDlAA/VAHIP1AAFDwIAAAErAASwAQ/VAAIfINUAcw8CABkB1QATIIsBD9UAAADdAQ8CBV0PhwABDwIAGg/VAKQP+AALD9UApA8CAAsR+dYAD38CqgHCAAcCAAL8BAW0BQ/VAQEPVAOPDdUAA8kAD6oBkgy9AAQCAAwYAACmAQAcAAAIAAACAAAMAAsCAAAXAAP0AA8CAFUPMQIBAIgFDxgABQEeAA8CABoP0QBcAAIAD70ABA8CADgEmQcPAgBYD9UATwB4Aw8CAFwP1QDDAmgGDwIASQ9VA2AAMAwP0wBJAFUDD1cDYA+DAk8P0QpdAKkBD9UAvAAaAg/TAE4PqgFdD9EAUAACAA9/AlsP1QD///9/A48DAwcADwIACw8pBIsDfQgHCgYP1QCxApIBD8oAEgcCAA+qAYsPAgAkD9UA////8g8HBRQPKQSWAdAAD7kMFA/VAIsMfQcP1QC6BAQQA+UADwIADQ+qAYEGuwABIAkCRhYBCAAGGgAPAgAKD9UAgQUCAADGAArxEgBaAwXaAAEfAAUtAAcCAA/VAFwAiAAHfgAPAgAQD9UACQ8/AAUP1QCgDwIADw/VAFwPkQAPDAIADqoBDwIADw/VAP//LApiBwZ/AgBlBAD+BA8CAA8PfwKBBLoAAcYAAgIAAdMAAHwaAQ8AA9cABQkADAIAD9UAgQcCAAO4AADLAAIWAAAKAAb1AAIUAA0CAA/VAFwAlAANhAAPAgAIAy4AAwcADwIAFQ/VAFwPlwAVCwIAD9UAwg8CABwPqgGTDwIAHA/VAP///xcDAAUDBwAPAgAMD1QDiwbEAAMKAAMHAA8CAAwP1QCSD8sAEwYCAA/VAIsDAgAP1QDCDwIAHQ+qAZIPAgAdD9UA////vQAvDgUCAA8KBB0PAgAMDykEZgZREQJNFg8CACYFGgEBAgABRwAP1QBnAYQAAQIADxEPJgACAAOVEQUCAAAZNg/VAGgAkwAAAgAW/wsADwIAIABRNgbCNw/VAHYGFBMPAgAhFvmmTwYCAAjcAg8CAE4E3RIBwhMBBwABAgABFwAFQQIPAgAWAjwAD9UAiw9TAR0D/QAP1QC7BAIAA0gDCAIAD38CdwSlAA8CAB4GKAQA+QQABgAP1QBtAUUCAB4DD4kAIQE9AAqqAQHiAA9MACEPAgAmARIEAgIAAI0AAAIAAEwAARcAD4kAHgNVFx/01QB5AM4AAwIAD9UAJAIeAQ/VAMQARgMFAgAPfwJrA6YBAAIAD6oBLAXRAAACAA/VAP8+CqEED14BIwBnBA8CAAUAAAIPAgBVCIQAB3QAAhcABxEADwIA/////////////////////0lQ//////8='b'eydyZXN1bHQnOiBbeydtYXBfdHlwZSc6IDAsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktdXMtc3RvcmFnZS1wZXJtYW5lbnQuaW90YmluZy5jb20vNjMzNzQ2LTE1MzAwMzg1OS0xMjN3NTY0N2MwYmEwNWRkMDY5Zi9jb21tb24vbGF5b3V0L2xheS5iaW4/Q0M9ZDg0OGVmNzYxMmEyNGQ0YzhjNWNlZjUzOGI5YzIyYmImQ1M9YjRlNTJjYTgyNDA0NzA0NTM0OTkxMTRlZWU2MjcxOGI2NTNjY2UyYzQyNjk0YmM3ODg3NGZiOTU4MWY3YzViYiZDRT0xNzE1MDk1NjkyMDA0JkNBPVYxJkNSPTInfSwgeydtYXBfdHlwZSc6IDEsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktdXMtc3RvcmFnZS1wZXJtYW5lbnQuaW90YmluZy5jb20vNjMzNzQ2LTE1MzAwMzg1OS0xMjN3NTY0N2MwYmEwNWRkMDY5Zi9jb21tb24vcm91dGUvcm91LmJpbj9DQz1kODQ4ZWY3NjEyYTI0ZDRjOGM1Y2VmNTM4YjljMjJiYiZDUz0yM2Q3NDZlYWRhOTM0ZmMwZDE0Zjc5YjdkNzdlYmRmNWFlY2JlZDk4NGY0NjFkZDhjY2ViNDY5NjVlOGJhNTFhJkNFPTE3MTUwOTU2OTIwMDgmQ0E9VjEmQ1I9Mid9LCB7J21hcF90eXBlJzogMywgJ21hcF91cmwnOiAnaHR0cHM6Ly90eS11cy1zdG9yYWdlLXBlcm1hbmVudC5pb3RiaW5nLmNvbS82MzM3NDYtMTUzMDAzODU5LTEyM3c1NjQ3YzBiYTA1ZGQwNjlmL2NvbW1vbi9yb3V0ZS9uYXYuYmluP0NDPWQ4NDhlZjc2MTJhMjRkNGM4YzVjZWY1MzhiOWMyMmJiJkNTPWE0ZDQ2Nzg4OGRiMWMzZGI4NWY5YmI2ODU3ZTc1MTg4MjUxMTdkYWNmZWI0N2EyNDk0MzdkZGQzOWI5NzJhYWYmQ0U9MTcxNTA5NTY5MjAxMiZDQT1WMSZDUj0yJ31dLCAnc3VjY2Vzcyc6IFRydWUsICd0JzogMTcxNTA5MjA5MjAxNCwgJ3RpZCc6ICcwODc5NDgwMDBjN2UxMWVmYTA5ODcyNGE4Yjc4ZWQxZSd9' Thank you!

**Comment by oven-lab** [comment]
Unsupported data format. Will not fix as of now, but save for the future.
