### ISSUE TITLE
[BUG] - Honiture Q6 Map format not supported

### ISSUE THREAD

**Issue by Wh1t3Rose** [oven-lab/tuya_cloud_map_extractor#44]
Added Honiture Q6 to Smart Life app. Device shows in Tuya Cloud IOT

Added Client ID / Clent Secret / Device ID to Integration.

**Version:**
 - OS: [ Unraid 6.12.6 /  Home Assistant OS.]
 - Version [e.g. 2024.5.5]

**Log entry**
Include the logs here. If possible, enable debug logging.

```
2024-05-26 19:00:32.236 ERROR (SyncWorker_38) [custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.main] Unsupported data type. Include the following data in a github issue to request the data format to be added: 200b'eyJkYXRhIjp7IkFsbG93Rm9yYmlkQXJlYSI6dHJ1ZSwiYXJlYSI6W10sImF1dG9BcmVhSWQiOjAsImJhc2U2NF9sZW4iOjM3MjgsImNoYXJnZUhhbmRsZVN0YXRlIjoibm90RmluZCIsImhlaWdodCI6MTI3LCJsejRfbGVuIjoyNzk0LCJtYXAiOiJIMzhCQVAvLy8vLy8vMFFmQUZJR2hxOEFmMzkvQUg4QS8vLy9vd0NEUWdEL2YvK2dBQStoQUlPQ0FQLy8vd0FBQVA4QkFBOUVBWDhFbWdBRUFnQVBvZ0FQRDJnQld3MmdBQTkvQUZzUEFnQU5CZG9CQmdJQUR6TUFDQWJOQUFieEF4TUFBUUFQTndBSUR3SUFKdytmQUFBTEtRTUJvQUlFWVFBRGl3QUtBZ0FSLzBVQUJyRUFEd0lBT1FGK0FBR1VBQWtDQUFCaEN5SUFmM3dBREFJQUNTa0FCd0lBRDVjQU9RWUNBQStmQUFJQlF3RWgvMzhKQUE4Q0FCVUdVd0FQQWdBNUR3OEJCeC8vb0FBY0JnVUNEd0lBT2craEFBa1Bvd0FiRHlRRFJBYVRBdzhDQUM4UEpBTkJENkFBakEvZ0FRc1BBZ0FMRFVFREQwQUJRQTgvQVRrUEl3TkJUUUQvZjM4SUFROENBQ1VIUUFFR05nVVB6d01zQXV3RUQrY0JLUVlDQUFLTkFBS2JBQVFXQUFJVUFBOENBQ2NDWEFrR1VBQVBBZ0FxQWUwS0N6TUNEM2dFTFFKUEFBSUdBQThDQUNRRlBRQUJPd0VQUlFBQUR6OEJKd1NnQUE4Q0FFa1BuZ0FwRDZBQVVBOVNDaXNQa0FFQ0R3SUFPZytnQUN3QmpBQVBwZ0JMRCtFQkN3RUJEUThqQUFraS93REZBdzhDQUVVRlB3TUJ3UVVGVmdvSWJ3QUhPZ1VPQWdBai93QmhEZzhDQUVRUkFBRUJCUUlBRDJZQUFRK2dBQW9YZjJFT0R3SUFaQStnQUFnR2ZnRVBBZ0JvRDZBQXB6OEEvMysvQTBRUGFnSUREd0lBQXc5QUFRY2hBUDhoQXcvbUFVRVBWQUFZRDZBQUJ3Q3NHUThnQTRvRGt3UVBlQUVERHdJQVZROUFBUXNQeFFOSkQvb0FFUjhBUVFZTUQ2QUFTUThDQUFFTU9nTWZBRUVCRGcvbUFCRVBBZ0FiRDFJQUNSRUFOUVFCZWdjREFnQVBRQUY3Q0FJQUFxa0FENEFDRGcvdkFBa1BBZ0ErQVRRRUJGWUFBdUVFQWFnRER3SUFDQStnQUZZQmZBSUVpUUFCblEwQkFRZ0JCd0FQQWdBSUQ2QUFRQVlqQVFJQ0FBRVFBQlFBZkFJSkFnQVBvQUJpRGJvVEFhRUFJZi8vRFFFSm53QVBnQUlWRDBVQlFBWUNBQUhPQVFMdUN5SC9meFlERHdJQUdBRklGUTZmQUFMN0JnNFlBQThDQUJ3Qk9RRUNxQkFDVEFBQkRBQVBud0FZQVZFREFib0NCQUlBQWhRQUFnSUFBbFFBRHdJQUl3YUlGUk4vS1FrQ1NBRVBRZ0VlQmFBQUFwUUFDQUlBRDZBQUtRRkFCQVBiQUFHYUFBSlpBQUlTQUFJTUFBOENBQlFoL3dBc0VnOENBQUFQb0FBcUNaWUJBWTBTQW1JQUFhSUFBZ3NBRHdJQUZRK2dBRUlGQWdBQnFRQUppd0FCTHdNQ29od1BBZ0FxRDBBQklnVTFBQUtJQUFHTUFBSkJBUWNDQUFJV0FBY1JBQThDQUNJQitnQVBBZ0F0QWxVRURlc1FBYUlBRDVZQUlnY0NBQVVNQVE4Q0FDc0Jad1FNQ2dnQlV3QUhiQUFQQWdBaEQ2QUFHUWN2QlFHU0R3R0FBQVlDQUE3T0FRSDNBUXkyQUE4Q0FCc1BvQUFPQVlvQUF3SUFBOUlSRlA4UEdRV2NBQUUvQVFJQ0FBcC9BQzhBQUlBSER3OENBQW9Qb0FBTUE1a0FCZ1FCQVlVQUJBOEFBUTBBQWdJQUI2SUFENHNDQUE4Q0FDY1BvQUFNQkFJQUJXRUFBUkVBQktBQUFqMEFCWnNBQlFrQUFnSUFCVFFBRHdJQUtRSmpBQThDQUFnS1hRQUNLUUFMb0FBVWY1d0FBVXdIQWlNQUFnSUFCQ2tBRHdJQUp3K2dBQTBNWWdBQmVBQUVGUUFDUFFBREZRQUlueDhCSmdBRGRSTVBBZ0FxRFlVRERBSUFCSXNBQkFJQUFTQUFCQlVBQXFBQUFlVUVEKzBFQUErZ0FEQVBlUWtCQ1FJQUJKY0FCUUlBQVI0QUM2QUFCcUVBQVFvQUR3SUFOdzhKQ3dBS0FnQU5hd0FDSHdBRW9BQUIxUUVCRXdBQ0RBQUJud29QQWdBMkFWa0FEd0lBQ2c1ckFBTXZBQVFaQUFTaEFBRUJDZ1lYQUE4Q0FERURhZ0FQQWdBS0RtZ0FCQzhBQXhvQUJROEFBU29HSC85QUFUY0VXUUFQQWdBTEE0WUFCd0lBQXpBQUJPRUJFd0JaQkFIYkFRRXdBQVljQUE4Q0FDZ0RaZ0FQQWdBT0RtTUFBY1lCQm9RQUFWY0tBaFFBQVlrQ0Fhd0xEallBRHdJQUhBK1lBQVVFelFZRklBQU9XQUFDakFBRmhBQUZvQUFIU0FFUEFnQXRCWDRBQ0FJQUFwc0FBbHNBQnFFQUFoQUFDQUlBQXpRQUJ1QUJCRE1HQks0SUNDMEFEd0lBSVFOaEFBd0NBQVJ4QUFFQ0FBTjNCUTl0QUFFRE9BQUpMd0FCMmdFRFl3UVBOQUFCRHdJQUdBTmZBQXdDQUFwQ0FBOUFBUW9DalFBS29BQUNGQUFCbmdVQ0t3TVBBZ0FqQlJjQkRBSUFDMDhBQmlnQUN4a0FBN3NBQjRBQ0JBSUFDVklBQkJVQUR3SUFId2xIQUFVQ0FBeElBQTlBQVFvQklRRU5OQUFHVEFBQklBQVBBZ0FlRVFCVUFBVkdBQWtDQUE1TkFBOUJBUWdDNWdRT05RQUVVZ0FDQ2dBT1V3QVBBZ0FNQm5JQURRSUFEem9BQUFZdUFBNGRBQUVEQXc4WkFBQURXQUFDd2dBUEp3Z2dBMWdBRGdJQURvTUFBMlFBQVRJQUFRNEFDQUlBQVJZQUR6WUFBQUl3QUFFeEFBRWpBQWcwQUE4Q0FCQUNMaEVEUlFBSEFnQVBPd0FEQlNFQURoOEFCQnNBRFJvQUF4a0FBeEFGRFI4QUR3SUFDUVB4QWcrZ0FBQVBOZ0FGQTIwQUR3Y0JBQUlhQUFUTEJRY0NBQUlaQUFJeUFBOUNBUndET3dBTm9BQVBid2dGQXpBQUQyWUFBZ0lYQUEvYUFBRUNHZ0FDc2dBUElnQUREd0lBQkFJNUFBUEdFUWNDQUE4dkFBUUlJQU1DRHdFSUFnQUNRQUFJRWdBRkFnQUJHd0FERGdBUG9RQVhBVFlBQVFJQUErY0JCQUlBQTBvQUR3SUFBZ1FrQUErZ0FBUU9LaEFEZHdJRk1nQUhDd0FQQWdBS0FTZ0FBd0lBQ3VBQkFkRUhEendBQkFNeEFBVnVBQWNDQUFJV0FBODZBQUlCR3dBQldRQUVBZ1FCQ2dBUEFnQUtDSlFBQ1VBQkR6WUFDZ0VuQmdFQ0FBNG5BQUZlQkErZ0FBa0VIQUFHckFBUEFnQUhDSjhBQ2F3TkR6TUFCd0VDQUFHY0FBOWhBQU1Qb0FBSUE5Y0FBVUlBQTBRQUF3d0FEd0lBQlFrekFRY05BQTh3QUFVREFnQUNuQUFQb0FBSUF5Z0FDZ0lBQlVFSEF4Y0FEMEFBQXdvQ0FBaEJBUVdnQUFvakFBOENBQUFDbkFBUFlBQURBb1lBQzJFSkFnSUFBaHNBQmpjQUJnb0FEd0lBQmcrZ0FBRVBMUUFHQlFJQUFtVUFEMThBQXdHRkFBVXFBQWtDQUFFYkFBRkpBZ01YQUFhTkFnOENBQVVQb0FBQUR5c0FCUWNDQUFGbUFBRUNBQWNWQUFNQ0FBR0ZBQU1NQUFzQ0FBRWJBQUVDQUFRWkFBK2hBQTRPb0FBRU93QVBBZ0FJQVdNQUFnSUFEaVlBQVJnQURoY0FBUklEQXg0QUJ5QUFENkVBRFFTZ0FCRi9kd0VQTGdBTkF3SUFBWU1BQWdJQUF4SUFCd0lBQVJnQUJ4QUFCd0lBQW1jQUNhQUFDdE1ERGdJQUJLQUFBcWtnRDFrQUJRc0NBQUprQUFFQ0FBc2FBQVJ4QUFFS0FBMENBQUZBRUFFM0FBZmlBd0VjRGcwckFBUUNBQVNnQUFFNUR3SU9EZzhDQUE4Q1l3QUJBZ0FPTFFBUEZ3QUVBZUFCQVJBa0FTRUFCNkVBRDJJZENnRmROZ0ZuQUI4QUZna0NEd0lBQWdKaUFBSUNBQTBoQUE4WEFBUUZvQUFEUWdFQ0VnQUJBZ0FGemc4UEFnQUFGd0JHQ1E4b0FBa0pBZ0FDZ3dBQ0FnQUpHUUFDaFFBUDZRQUdBeTRBQ3prQUNGNFhEUUlBQVhNZkRSWUFEd0lBREFKaEFBSUNBQTByQUFGcEF3MFdBQUlDQUFQV0FRSTZBQU1OQUE4Q0FBMFBKd0FVQ0FJQUEyQUFBUUlBQ0JnQUFRSUFEeE1BQUFVQ0FBUTVDQUhFQUE5akJnSU5BZ0FQN0FBR0R3SUFDQUdaQUFNQ0FBMG5BQThUQUFBRkFnQUVIQUFQV0M0dER3SUFDd09hQUFJQ0FBMHJBQThUQUFBRkFnQVBIQUFKRHdJQU53S1pBQU1DQUExWEFBOFRBQUFQQWdCY0E1b0FBZ0lBRFh3QUR4TUFBQThDQUZ3Q21RQURBZ0FOZkFBUEV3QUFEd0lBWEFPYUFBSUNBQTE4QUE4VEFBQVBBZ0JjQXBrQUF3SUFEWHdBRHhNQUFBOENBRnNEbVFBREFnQU5mQUFQRXdBQUR3SUFXd09aQUFNQ0FBMThBQThUQUFBUEFnQmJBNWtBQXdJQURYd0FEeE1BQUE4Q0FGc0RtUUFDQWdBT2V3QUJjZ2dQQWdCcEFwa0FBUUlBQWk0VkN3SUFEd2NKRmc4Q0FFVUJtd0FDVndnUDVnY1ZEd0lBV2dlbkN3K0VDQk1QQWdCYkl3QUFZVDBQaGdoTER3SUEvLy8vLy8vL0pWQi9mMzkvZnc9PSIsIm1hcElkIjoxNzE2NzU5MzMyLCJwYXRoSWQiOjE3MTY3NTkzMzEsInJlc29sdXRpb24iOjAuMDUwMDAwMDAwNzQ1MDU4MDYsIndpZHRoIjoxNjAsInhfbWluIjotNC44MjQ0MzY2NjQ1ODEyOTg4LCJ5X21pbiI6LTIuMDI1MDAwNTcyMjA0NTg5OH0sImluZm9UeXBlIjoyMDAwMn0='b'eydyZXN1bHQnOiBbeydtYXBfdHlwZSc6IDAsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktdXMtc3RvcmFnZS1wZXJtYW5lbnQuaW90YmluZy5jb20vNWNiZjZhLTE5NDI1MzAxMi1hYmNkNGI4NGIwNzcxZDA3NGZlOS9jb21tb24vbGF5b3V0L2xheS5iaW4/Q0M9ZDg0OGVmNzYxMmEyNGQ0YzhjNWNlZjUzOGI5YzIyYmImQ1M9NzM2YTMwOWIwNDFlYWRlNzdhYzY1YjQ2MDgwZjU1MjU3ZDlmNzNlOWIwMTNjOGU0MGVlZGIzNmUzNmExN2EyYSZDRT0xNzE2Nzc4ODQ4OTQ4JkNBPVYxJkNSPTInfV0sICdzdWNjZXNzJzogVHJ1ZSwgJ3QnOiAxNzE2Nzc1MjQ4OTUwLCAndGlkJzogJ2YwMzMzMTQ3MWJjYzExZWY5YjFiYjYyNjQxNjA1MzQ1J30=' Thank you!
2024-05-26 19:00:32.237 ERROR (MainThread) [custom_components.tuya_cloud_map_extractor.config_flow] 'chargeHandlePos'
Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
    headers, image = await validate(self.hass, user_input)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 154, in get_map
    raise e
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 144, in get_map
    header, mapDataArr = parse_map(response)
                         ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 31, in parse_map
    header, mapDataArr = decode_custom0(data)
                         ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/custom0.py", line 45, in decode_custom0
    "pileX": data["data"]["chargeHandlePos"][0],
             ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'chargeHandlePos'

**Comment by Wh1t3Rose** [comment]
Solved. Redid map and resized rooms/sections. Issue resolved.
