### ISSUE TITLE
[BUG] - Unable to set up integration

### ISSUE THREAD

**Issue by martinjcxn** [oven-lab/tuya_cloud_map_extractor#46]
**Describe the bug**

**To Reproduce**
1. Set up Tuya cloud app account as per instructions
2. Add integration
3. Input values

**Expected behavior**
Completion of integration set up.

**Screenshots**
![image](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/95468337/0027848f-b985-4f89-9ffd-4bcb3c0dca8e)

**Version:**
HAOS: Generic x86-64 Machine
![image](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/95468337/337f70b1-1846-453d-a9ad-dd0181158465)

**Log entry**
2024-05-30 14:15:09.887 ERROR (MainThread) [custom_components.tuya_cloud_map_extractor.config_flow] bytearray index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 30, in parse_map
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
    headers, image = await validate(self.hass, user_input)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 154, in get_map
    raise e
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 144, in get_map
    header, mapDataArr = parse_map(response)
                         ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 37, in parse_map
    mapDataArr = decode_v0(data, header)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/v0.py", line 34, in decode_v0
    decodeDataArray = uncompress(encodeDataArray)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/pylz4/lz4.py", line 102, in uncompress
    dst.append(dst[-offset])

**Comment by jack3308** [comment]
Think I'm running into something similar, any luck with this on your own yet?

**Comment by martinjcxn** [comment]
> Think I'm running into something similar, any luck with this on your own yet?

Nah - unfortunately not. From what I can tell the map version doesn't seem to be supported but not sure how to fix it.
