### ISSUE TITLE
[BUG] - EOF at reading literal-len

### ISSUE THREAD

**Issue by wejto** [oven-lab/tuya_cloud_map_extractor#48]
**Describe the bug**
When trying to set-up the integration I get the EOF at reading literal-len error indicating that the buffer is empty. This is more asking for help and trying to figure out what's wrong and why that happen that reporting bug as the piece of code seems to be reasonable and I just do not know why nothing has been returned. The Sweeping Robot Open Service is on.

**Screenshots**
![image](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/35685467/83231e76-405f-465c-9066-1582974d4385)

**Log entry**
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 963, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 30, in parse_map
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
    headers, image = await validate(self.hass, user_input)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 154, in get_map
    raise e
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 144, in get_map
    header, mapDataArr = parse_map(response)
                         ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 39, in parse_map
    mapDataArr = decode_v1(data, header)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/v1.py", line 147, in decode_v1
    raw = uncompress(encodeDataArray)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/pylz4/lz4.py", line 71, in uncompress
    raise CorruptError("EOF at reading literal-len")
custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.pylz4.lz4.CorruptError: EOF at reading literal-len

**Comment by wejto** [comment]
Oh! I just found out another message in the log so including it here hoping it will help out :)

> Unsupported data type. Include the following data in a github issue to request the data format to be added: 200b'AQABAAAAAAAAAAAAAAUAAAAAAAAAAAAA'b'eydyZXN1bHQnOiBbeydtYXBfdHlwZSc6IDAsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktZXUtc3RvcmFnZS1wZXJtYW5lbnQudHV5YWV1LmNvbS8wYTQ0MzEtMTYxODE3OTI5LWptc3g5YzViY2YzYTI4MmJkMGM3L2NvbW1vbi9sYXlvdXQvbGF5LmJpbj9DQz1kODQ4ZWY3NjEyYTI0ZDRjOGM1Y2VmNTM4YjljMjJiYiZDUz03NTgxMmYzMTA2MjcyN2Q5YmIyMWY3YTAxMDJiNWNmZDQxNDliZTk4MjlmMGExYjAzNjQ4ZmRiOTc4NzE3MjMwJkNFPTE3MTkzOTA5MTg5MjgmQ0E9VjEmQ1I9Mid9LCB7J21hcF90eXBlJzogMSwgJ21hcF91cmwnOiAnaHR0cHM6Ly90eS1ldS1zdG9yYWdlLXBlcm1hbmVudC50dXlhZXUuY29tLzBhNDQzMS0xNjE4MTc5Mjktam1zeDljNWJjZjNhMjgyYmQwYzcvY29tbW9uL3JvdXRlL3JvdS5iaW4/Q0M9ZDg0OGVmNzYxMmEyNGQ0YzhjNWNlZjUzOGI5YzIyYmImQ1M9YTlhNWY0YWU2ZGU2MjMwNjRkYjVmZDI5MjMwNGMzNjdjNDgzOGZmM2FjYjg5ODYwNzc2NWRmODRhY2JlNDI2YiZDRT0xNzE5MzkwOTE4OTMxJkNBPVYxJkNSPTInfSwgeydtYXBfdHlwZSc6IDMsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktZXUtc3RvcmFnZS1wZXJtYW5lbnQudHV5YWV1LmNvbS8wYTQ0MzEtMTYxODE3OTI5LWptc3g5YzViY2YzYTI4MmJkMGM3L2NvbW1vbi9yb3V0ZS9uYXYuYmluP0NDPWQ4NDhlZjc2MTJhMjRkNGM4YzVjZWY1MzhiOWMyMmJiJkNTPTc5MjUxOTc5NTBjMzVhZTY4NGNjOGVhMTEzZTVmOWU2YWE1MWIwMTk5YTFjOWM1Yjk5Njg4ZDkxZmU2Njc3ZjImQ0U9MTcxOTM5MDkxODkzNSZDQT1WMSZDUj0yJ31dLCAnc3VjY2Vzcyc6IFRydWUsICd0JzogMTcxOTM4NzMxODkzNywgJ3RpZCc6ICdhMzNkMjNjYTMzOGUxMWVmYWVkNmY2MTVlODU0ZDc1Myd9' Thank you!
