### ISSUE TITLE
[BUG] - An unknown error occured. See logs for details.

### ISSUE THREAD

**Issue by jack3308** [oven-lab/tuya_cloud_map_extractor#51]
**Describe the bug**
Similar error to [#16](https://github.com/oven-lab/tuya_cloud_map_extractor/issues/16#issue-2052455414), however the [steps](https://github.com/oven-lab/tuya_cloud_map_extractor/issues/16#issuecomment-1866408356) to resolve that issue didn't work.

**To Reproduce**
1. Install Integration
2. Reboot
3. Enable relevant APIs in Tuya Developer acct
4. Setup integration using config flow with relevant and verified info
5. Unknown Error returned

**Screenshot**
![Dot Error 240822](https://github.com/user-attachments/assets/45391809-61d9-4fc3-a791-3cc031db5346)

**Error Text**

> - Encountered an error, please include the following data in your github issue: b'eyJyZXN1bHQiOiBbXSwgInN1Y2Nlc3MiOiB0cnVlLCAidCI6IDE3MjQyOTk2NDgzMjIsICJ0aWQiOiAiMGJiMDgyZjU2MDNjMTFlZjlhOGM0NjA0YWViZWY4MzcifQ=='
> - Encountered an error, please include the following data in your github issue: b'eyJyZXN1bHQiOiBbXSwgInN1Y2Nlc3MiOiB0cnVlLCAidCI6IDE3MjQzMDAwNzI5OTcsICJ0aWQiOiAiMDhkNzgxZWQ2MDNkMTFlZjk1YTNjMjgzYWU5YWE5MDgifQ=='

**Version:**
 - OS: Home Assistant OS on RaspberryPi 4b
 -  Core 2024.8.1
 - Supervisor 2024.08.0
 - Operating System 13.0
 - Frontend 20240809.0

**Device**
[Kogan LX18](https://www.kogan.com/au/buy/kogan-smarterhome-lx18-pro-robot-vacuum-cleaner-and-mop-with-auto-empty-dock/)

**Log entry**
Encountered an error, please include the following data in your github issue: b'eyJyZXN1bHQiOiBbXSwgInN1Y2Nlc3MiOiB0cnVlLCAidCI6IDE3MjQyOTk2NDgzMjIsICJ0aWQiOiAiMGJiMDgyZjU2MDNjMTFlZjlhOGM0NjA0YWViZWY4MzcifQ==

**Comment by PeterGillham** [comment]
Same error as above
OS: Home Assistant OS on X86-64 Debian
Core 2024.8.3
Supervisor 2024.08.0
Operating System Debian 12
Frontend 20240809.0

Device: Lafant M820 connected to Smart Life OK

**Comment by mgluchgit** [comment]
I have the same problem....

Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
    headers, image = await validate(self.hass, user_input)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 131, in get_map
    raise e
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 127, in get_map
    map_link = link["result"][0]["map_url"]
               ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
