### ISSUE TITLE
No permissions. This API is not subscribed.

### ISSUE THREAD

**Issue by eph2** [oven-lab/tuya_cloud_map_extractor#52]
Hey there! I'm trying to download the map from my vaccum, but when I insert my credentials, this error return:

> An unknown error occured. See logs for details.

This is the log message:

`Este erro originou-se de uma integração personalizada.

Registrador: custom_components.tuya_cloud_map_extractor.config_flow
Fonte: custom_components/tuya_cloud_map_extractor/config_flow.py:57
integração: Tuya Cloud Map Extractor (documentação, problemas)
Ocorreu pela primeira vez: 12:23:08 (3 ocorrências)
Último registro: 12:34:01

('Request failed - Response: ', {'code': 28841101, 'msg': 'No permissions. This API is not subscribed.', 'success': False, 't': 1725636188521, 'tid': 'ebc31d1c6c6311ef86b3722f08288c6c'})
('Request failed - Response: ', {'code': 28841101, 'msg': 'No permissions. This API is not subscribed.', 'success': False, 't': 1725636198621, 'tid': 'f1cc4c106c6311ef86b3722f08288c6c'})
('Request failed - Response: ', {'code': 28841101, 'msg': 'No permissions. This API is not subscribed.', 'success': False, 't': 1725636841341, 'tid': '70d142636c6511efbcbd7aea62a19b8a'})
Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
    headers, image = await validate(self.hass, user_input)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 124, in get_map
    link = get_download_link(server, client_id, secret_key, device_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/tuya.py", line 68, in get_download_link
    raise RuntimeError("Request failed - Response: ", response)
RuntimeError: ('Request failed - Response: ', {'code': 28841101, 'msg': 'No permissions. This API is not subscribed.', 'success': False, 't': 1725636188521, 'tid': 'ebc31d1c6c6311ef86b3722f08288c6c'})`

I don't know if I configured the "Tuya Cloud Developer" info right, but if you have some tip, please, let me know!

**Comment by Rom4ik57rus** [comment]
Cloud>Cloud Services>Sweeping Robot Open Service>Free trial
